### ISSUE TITLE
Compilation to JavaScript fails

### ISSUE THREAD

**Issue by sheremetyev** [jordwalke/ReasonExampleProject#4]
Followed instructions at http://facebook.github.io/reason/projects.html.

After this command
~~~
node ./node_modules/CommonML/build.js --forDebug=true --jsCompile=true
~~~

the following error is produced

~~~
Uncaught exception.

Stack Trace:
------------
 Error: You have asked to compile to JavaScript but the binary `js_of_ocaml` is not in your path. You probably also want to add an item to your package.json's CommonML "findlibPackages": [{"dependency": "js_of_ocaml"}]
    at /Users/fedor/Sandbox/ReasonExampleProject/node_modules/CommonML/build.js:2613:13
    at /Users/fedor/Sandbox/ReasonExampleProject/node_modules/whereis/index.js:14:26
    at ChildProcess.exithandler (child_process.js:209:5)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
~~~

Mac OS X 10.11.5. Reason installed as suggested at https://github.com/facebook/reason/blob/master/README.md#install-stable

**Comment by sheremetyev** [comment]
This fixes the problem.

~~~
$ opam install js_of_ocaml
~~~

**Comment by tsaiDavid** [comment]
@sheremetyev - thanks!
@jordwalke - I ran into the same issue, I'd be happy to help with this. Could the simplest fix simply be just throwing in a postinstall script which runs the install command?

**Comment by jordwalke** [comment]
@tsaiDavid Ideally, we'd bundle js_of_ocaml as an `npm` dependency, so it could never fail. That will take some time to get working correctly, and maybe BuckleScript would be a better option. But before then, I hesitate to just install stuff into people's global namespace without them knowing about it, so maybe a better error message would be in order (include the opam command to install it).
